name: build api image
on:
  push:
    branches: [ main ]
    paths:
      - "apps/fitcoach-api/**"
      - ".github/workflows/api.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: viktdo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (fitcoach-api)
        uses: docker/build-push-action@v5
        with:
          context: ./apps/fitcoach-api
          file: ./apps/fitcoach-api/Dockerfile
          push: true
          tags: |
            ghcr.io/viktdo/fitcoach-api:main
            ghcr.io/viktdo/fitcoach-api:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
