name: Build & Push - API

on:
  push:
    paths:
      - "apps/fitcoach-api/**"
      - ".github/workflows/api.yml"
    branches: [ main, staging ]

permissions:
  contents: read
  packages: write

concurrency:
  group: build-api-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fitcoach-api

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/fitcoach-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:${{ github.ref_name == 'main' && 'main' || 'staging' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max