name: deploy to vps

on:
  workflow_run:
    workflows: ["build-and-push-images"]  # <=== ИМЯ из containers.yml (name:)
    types: [completed]
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-main
      cancel-in-progress: false

    steps:
      - name: Prepare SSH key and known_hosts
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/fitcoach_deploy
          chmod 600 ~/.ssh/fitcoach_deploy
          ssh-keyscan -t ed25519 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: SSH smoke test
        run: |
          ssh -i ~/.ssh/fitcoach_deploy \
              -o BatchMode=yes \
              -o StrictHostKeyChecking=yes \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo ok && hostname && whoami"

      - name: Run deploy script
        run: |
          ssh -i ~/.ssh/fitcoach_deploy \
              -o BatchMode=yes \
              -o StrictHostKeyChecking=yes \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "/root/apps/deploy.sh"